#!/bin/sh
#npm install -g doxx
set -e
git stash
git branch gh-pages | echo 'Create branch gh-pages if it does not exist'
git checkout gh-pages
doxx --source lib --target . --title 'milojs'
git add .
git add -u .
git commit -m 'doxx generated'
git push --force origin gh-pages
git checkout master
git branch -D gh-pages
